import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<meta name="theme-color" content="#4161F4" />
			</head>
			<body className={`${inter.className} !text-[#f2f2f2]`}>
				<nav className="fixed w-full">
					<div className="flex justify-between w-11/12 mx-auto h-[82px] items-center ">
						<Link href="/" className="text-[26px] font-light text-[#f2f2f2]">
							Ahmet Kilinç
						</Link>
						{/* <img src="/menu.svg" alt="menu icon" /> */}
					</div>
				</nav>
				{children}
			</body>
		</html>
	);
}
